export { default as DocsThemeLayout } from '@/theme/layout'
export { Button } from '@/theme/button'
export type { ButtonProps, ButtonVariant, ButtonSize } from '@/theme/button'
export { Navbar } from '@/theme/navbar'
export { Sidebar } from '@/theme/sidebar'
export { OnThisPage } from '@/theme/on-this-page'
export { Feedback } from '@/theme/feedback'
export { DocsTabs } from '@/theme/tabs'
export { I18nSelector } from '@/theme/i18n-selector'
export { Section } from '@/theme/section'
