import { useState } from 'react'
import {
  CircleDot,
  Clock,
  Hammer,
  CheckCircle2,
  LoaderCircle,
} from 'lucide-react'
import { cn } from 'boltdocs/client'
import { Section } from '@/theme/section'

type RoadmapItem = {
  title: string
  description: string
  status: 'in-progress' | 'planning'
}

const ROADMAP: RoadmapItem[] = [
  // In Progress
  {
    title: 'Boltdocs migrate MVP — VitePress first',
    description:
      'A first-party migration tool to move existing VitePress sites to Boltdocs with minimal friction.',
    status: 'in-progress',
  },
  {
    title: 'Instant Navigation',
    description:
      'Prefetching, View Transitions, and no page reloads for buttery-smooth navigation.',
    status: 'in-progress',
  },
  {
    title: 'Redirects',
    description:
      'Declarative redirects via config with 301/308 support and loop detection.',
    status: 'in-progress',
  },
  {
    title: 'Virtual routes',
    description:
      'Routes generated by plugins, unlocking fully dynamic documentation trees.',
    status: 'in-progress',
  },
  // Planning
  {
    title: 'Search & primitive improvements',
    description: 'Consolidate the public API and harden the search primitives.',
    status: 'planning',
  },
  {
    title: 'Plugin: tabs-sync',
    description: 'Tabs that stay in sync across pages on the same visit.',
    status: 'planning',
  },
  {
    title: 'Plugin: reading-time',
    description: 'Reading time derived automatically from content.',
    status: 'planning',
  },
  {
    title: 'Plugin: last-updated',
    description: 'Last-updated dates sourced from git history.',
    status: 'planning',
  },
  {
    title: 'Plugin: contributors',
    description: 'Author and contributor lists derived from git.',
    status: 'planning',
  },
  {
    title: 'Plugin: video',
    description: 'Embed YouTube, Loom, and Vimeo natively.',
    status: 'planning',
  },
  {
    title: 'Plugin: code-diff',
    description: 'Diffs tailored for migration guides.',
    status: 'planning',
  },
  {
    title: 'Plugin: shiki-twoslash',
    description: 'Inline TypeScript type annotations in code blocks.',
    status: 'planning',
  },
  {
    title: 'Plugin: cookie-consent',
    description: 'GDPR-ready cookie consent banners.',
    status: 'planning',
  },
  {
    title: 'Plugin: plausible',
    description: 'Privacy-first, lightweight analytics.',
    status: 'planning',
  },
  {
    title: 'Plugin: Fathom',
    description: 'Privacy-first website analytics integration.',
    status: 'planning',
  },
  {
    title: 'Plugin: pagefind',
    description: 'Local, backend-free search for your docs.',
    status: 'planning',
  },
  {
    title: 'Plugin: utterances',
    description: 'GitHub-based comments for docs pages.',
    status: 'planning',
  },
  {
    title: 'Plugin: hotjar',
    description: 'Heatmaps and session replay.',
    status: 'planning',
  },
  {
    title: 'Plugin: meilisearch',
    description: 'Self-hosted full-text search.',
    status: 'planning',
  },
  {
    title: 'Plugin: directive',
    description: 'Custom directives within MDX content.',
    status: 'planning',
  },
  {
    title: 'Plugin: storybook',
    description: 'Embed Storybook stories in your docs.',
    status: 'planning',
  },
  {
    title: 'create-plugin scaffolder',
    description: 'Official CLI scaffolder for new Boltdocs plugins.',
    status: 'planning',
  },
  {
    title: 'Full migration tool',
    description:
      'A comprehensive tool to migrate any existing documentation setup to Boltdocs.',
    status: 'planning',
  },
]

const STATUS_META = {
  'in-progress': {
    label: 'In Progress',
    icon: LoaderCircle,
    accent: 'text-accent-400',
    badgeBg: 'bg-accent-500/10 text-accent-400',
    bar: 'bg-linear-to-r from-accent-500 to-primary-500',
  },
  planning: {
    label: 'Planning',
    icon: CircleDot,
    accent: 'text-muted',
    badgeBg: 'bg-subtle text-muted',
    bar: 'bg-dim/40',
  },
} as const

function RoadmapItemCard({ item }: { item: RoadmapItem }) {
  const meta = STATUS_META[item.status]
  const Icon = meta.icon

  return (
    <div className="group flex items-start gap-5 p-5 rounded-2xl bg-surface">
      <div
        className={`mt-0.5 shrink-0 flex items-center justify-center size-10 rounded-xl ${meta.badgeBg}`}
      >
        <Icon className="w-5 h-5" />
      </div>
      <div className="flex-1 min-w-0">
        <h3 className="text-base font-semibold text-body leading-snug">
          {item.title}
        </h3>
        <p className="mt-1.5 text-sm text-paragraph leading-relaxed">
          {item.description}
        </p>
      </div>
      <span className="hidden sm:inline-flex h-6 shrink-0 items-center rounded-full px-3 text-xs font-medium">
        {item.status === 'in-progress' ? (
          <span className="flex items-center gap-1.5 rounded-full bg-accent-500/10  px-2.5 py-0.5 text-accent-400">
            <LoaderCircle className="w-3 h-3 animate-spin" /> Active
          </span>
        ) : (
          <span className="flex items-center gap-1.5 rounded-full bg-subtle px-2.5 py-0.5 text-muted">
            <Clock className="w-3 h-3" /> Planned
          </span>
        )}
      </span>
    </div>
  )
}

export default function RoadmapPage() {
  const [tab, setTab] = useState<'all' | 'in-progress' | 'planning'>('all')

  const inProgress = ROADMAP.filter((i) => i.status === 'in-progress')
  const planning = ROADMAP.filter((i) => i.status === 'planning')
  const visible =
    tab === 'all' ? ROADMAP : tab === 'in-progress' ? inProgress : planning

  const tabs = [
    { key: 'all' as const, label: `All (${ROADMAP.length})` },
    {
      key: 'in-progress' as const,
      label: `In Progress (${inProgress.length})`,
    },
    { key: 'planning' as const, label: `Planning (${planning.length})` },
  ]

  return (
    <div className="font-sans antialiased min-h-screen text-body relative overflow-hidden">
      <Section padding="xl" maxWidth="lg">
        <div className="text-center mb-6">
          <h1 className="text-4xl md:text-6xl font-black tracking-tighter text-body mb-6">
            What&apos;s coming next
          </h1>
          <div className="mt-8 flex items-center justify-center gap-6 text-sm">
            <span className="flex items-center gap-2 text-paragraph">
              <span className="size-2.5 rounded-full bg-accent-500 animate-pulse" />
              {inProgress.length} in progress
            </span>
            <span className="flex items-center gap-2 text-paragraph">
              <span className="size-2.5 rounded-full bg-dim/60" />
              {planning.length} planned
            </span>
          </div>
        </div>

        <div className="flex justify-center mb-10">
          <div className="inline-flex items-center gap-1 p-1 rounded-full bg-surface">
            {tabs.map((t) => (
              <button
                key={t.key}
                onClick={() => setTab(t.key)}
                className={cn(
                  `px-5 py-2 rounded-full text-sm font-medium transition-all duration-300 cursor-pointer`,
                  {
                    'bg-primary-500/15 text-primary-300 border border-primary-500/25':
                      tab === t.key,
                    'text-muted hover:text-body border border-transparent':
                      tab !== t.key,
                  },
                )}
              >
                {t.label}
              </button>
            ))}
          </div>
        </div>

        {tab === 'all' ? (
          <div className="flex flex-col">
            <section className="mb-14">
              <div className="flex items-center gap-3 mb-6">
                <div className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-accent-500/10 border border-accent-500/25 text-accent-400 text-sm font-semibold">
                  <Hammer className="size-16" />
                  In Progress
                </div>
                <div className="h-px flex-1 bg-subtle" />
              </div>
              <div className="flex flex-col gap-4">
                {inProgress.map((item) => (
                  <RoadmapItemCard key={item.title} item={item} />
                ))}
              </div>
            </section>

            <section>
              <div className="flex items-center gap-3 mb-6">
                <div className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-surface border border-subtle text-muted text-sm font-semibold">
                  <CheckCircle2 className="size-16" />
                  Planning
                </div>
                <div className="h-px flex-1 bg-subtle" />
              </div>
              <div className="grid sm:grid-cols-2 gap-4">
                {planning.map((item) => (
                  <RoadmapItemCard key={item.title} item={item} />
                ))}
              </div>
            </section>
          </div>
        ) : (
          <div
            className={
              tab === 'in-progress'
                ? 'flex flex-col gap-4'
                : 'grid sm:grid-cols-2 gap-4'
            }
          >
            {visible.map((item) => (
              <RoadmapItemCard key={item.title} item={item} />
            ))}
          </div>
        )}
      </Section>
    </div>
  )
}
