import fs from 'node:fs'
import path from 'node:path'
import type { BoltdocsConfig } from '../shared/types'

/**
 * Generates a declaration file (.boltdocs/types.d.ts) to provide strict typing 
 * for locales and versions based on the project configuration.
 */
export function generateProjectTypes(config: BoltdocsConfig, root: string = process.cwd()) {
  const dotBoltdocsDir = path.resolve(root, '.boltdocs')
  if (!fs.existsSync(dotBoltdocsDir)) {
    fs.mkdirSync(dotBoltdocsDir, { recursive: true })
  }

  const locales = config.i18n ? Object.keys(config.i18n.locales) : []
  const versions = config.versions ? config.versions.versions.map(v => v.path) : []

  const localeType = locales.length > 0 ? locales.map(l => `'${l}'`).join(' | ') : 'string'
  const versionType = versions.length > 0 ? versions.map(v => `'${v}'`).join(' | ') : 'string'

  const content = `// This file is automatically generated by Boltdocs.
// Do not edit this file manually.

declare global {
  namespace Boltdocs {
    interface Types {
      Locale: ${localeType}
      Version: ${versionType}
    }
  }
}

export {}
`

  fs.writeFileSync(path.resolve(dotBoltdocsDir, 'types.d.ts'), content)
}
