import React from 'react'
import type { BoltdocsConfig } from '@node/config'

/**
 * Metadata provided by the server for a specific route.
 * Maps closely to the `RouteMeta` type in the Node environment.
 */
export interface ComponentRoute {
  /** The final URL path */
  path: string
  /** The absolute filesystem path of the source file */
  componentPath: string
  /** The page title */
  title: string
  /** Explicit order in the sidebar */
  sidebarPosition?: number
  /** The relative path from the docs directory */
  filePath: string
  /** The group directory name */
  group?: string
  /** The display title of the group */
  groupTitle?: string
  /** Explicit order of the group in the sidebar */
  groupPosition?: number
  /** Extracted markdown headings for search indexing */
  headings?: { level: number; text: string; id: string }[]
  /** The page summary or description */
  description?: string
  /** The locale this route belongs to, if i18n is configured */
  locale?: string
  /** The version this route belongs to, if versioning is configured */
  version?: string
  /** Optional icon to display (Lucide icon name or raw SVG) */
  icon?: string
  /** The tab this route belongs to, if tabs are configured */
  tab?: string
  /** Optional badge to display next to the sidebar item */
  badge?: string | { text: 'updated' | 'new' | 'deprecated'; expires?: string }
  /** Optional icon for the route's group */
  groupIcon?: string
  /** The extracted plain-text content of the page for search indexing */
  _content?: string
  /** The raw markdown content of the page */
  _rawContent?: string
}

/**
 * Site configuration provided by the server.
 */
export type SiteConfig = BoltdocsConfig

/**
 * Configuration options for initializing the Boltdocs client app.
 */
export interface CreateBoltdocsAppOptions {
  /** CSS selector for the DOM element where the app should mount (e.g. '#root') */
  target: string
  /** Initial routes generated by the Vite plugin (`virtual:boltdocs-routes`) */
  routes: ComponentRoute[]
  /** The name of the documentation directory (e.g. 'docs') */
  docsDirName: string
  /** Site configuration (`virtual:boltdocs-config`) */
  config: SiteConfig
  /** Dynamic import mapping from `import.meta.glob` for the documentation pages */
  modules: Record<string, () => Promise<{ default: React.ComponentType }>>
  /** The `import.meta.hot` instance necessary for fast refresh/HMR updates */
  hot?: {
    accept: (cb?: (mod: any) => void) => void
    dispose: (cb: (data: any) => void) => void
    on: (event: string, cb: (data: any) => void) => void
    data: any
  }
  /** Optional custom React component to render when visiting the root path ('/') */
  homePage?: React.ComponentType
  /** Custom external pages mapped by their route path */
  externalPages?: Record<string, React.ComponentType>
  /** Optional custom MDX components provided by plugins */
  components?: Record<string, React.ComponentType>
}

/**
 * Types for CodeSandbox integration.
 */
export interface SandboxFile {
  content: string | object
  isBinary?: boolean
}

export type SandboxFiles = Record<string, SandboxFile>

export interface SandboxOptions {
  files?: SandboxFiles
  dependencies?: Record<string, string>
  devDependencies?: Record<string, string>
  title?: string
  description?: string
  template?: string
  /** The file path to open by default in the editor (e.g. `"src/App.tsx"`). */
  entry?: string
  /** Options for the embedded iframe view, used by `embedSandbox()`. */
  embed?: SandboxEmbedOptions
  /** Custom scripts for the package.json (e.g. `{ "start": "vite" }`). */
  scripts?: Record<string, string>
  /** Optional default theme configuration for the sandbox project. */
  themeConfig?: Record<string, unknown>
}

export interface SandboxEmbedOptions {
  /** Which panel to display: `"editor"`, `"preview"`, or `"split"`. */
  view?: 'editor' | 'preview' | 'split'
  /** Color theme: `"dark"` or `"light"`. */
  theme?: 'dark' | 'light'
  /** Whether to hide the navigation bar in the embed. */
  hideNavigation?: boolean
}

/**
 * Tab configuration for the documentation site.
 */
export interface BoltdocsTab {
  id: string
  text: string
  icon?: string
}

/**
 * Props for the Sidebar component.
 */
export interface SidebarProps {
  routes: ComponentRoute[]
  config: BoltdocsConfig
}

/**
 * Props for the OnThisPage (TOC) component.
 */
export interface OnThisPageProps {
  headings?: { level: number; text: string; id: string }[]
  editLink?: string
  communityHelp?: string
  filePath?: string
}

/**
 * Props for the Tabs component.
 */
export interface TabsProps {
  tabs: BoltdocsTab[]
  routes: ComponentRoute[]
}

/**
 * Props for user-defined layout components (layout.tsx).
 */
export interface LayoutProps {
  children: React.ReactNode
}

/**
 * Unified type for navbar links.
 */
export interface NavbarLink {
  label: string
  href: string
  active: boolean
  /** Optional icon or string for external link indication */
  to?: string
  /** Nested items for NavigationMenu */
  items?: NavbarLink[]
}
